### ISSUE TITLE
koa-router error

### ISSUE THREAD

**Issue by mniehe** [appneta/node-traceview#163]
I'm getting an error when I try to start up my app with Traceview installed. Anyone have suggestions?

See below for details:

```js
/app/node_modules/traceview/dist/probes/koa-router.js:22
      return typeof v[method] === 'function';
                     ^

TypeError: Cannot read property 'acl' of undefined
    at /app/node_modules/traceview/dist/probes/koa-router.js:22:22
    at Array.filter (native)
    at /app/node_modules/traceview/dist/probes/koa-router.js:21:32
    at Array.forEach (native)
    at patchApp (/app/node_modules/traceview/dist/probes/koa-router.js:19:25)
    at /app/node_modules/traceview/dist/probes/koa-router.js:12:12
    at Object.<anonymous> (/app/src/controllers/index.js:2:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
```

The versions I'm using:
- koa: 1.2.0
- koa-router: 5.4.0
- traceview: 2.7.0
- node: 6.2.1

**Comment by Qard** [comment]
Fixed by #164 and released as 2.7.1.
